### ISSUE TITLE
Crashes since #5

### ISSUE THREAD

**Issue by sneak-it** [GAMMACASE/MomSurfFix#6]
The plugin causes crashes with #5 on Windows servers. Linux appears to do just fine, but Windows does not like the change. No error logs.

SM Version: 1.10.0.6492
CS:GO Version: 1.37.7.0
Dhooks Detours Versions tested: detours9, detours15

No error logs are produced, however I do have several accelerator links that are fairly unhelpful as far as I can tell:
https://crash.limetech.org/m4ncxggmmvzz
https://crash.limetech.org/7k5qdsudjj72
https://crash.limetech.org/zmvqcz3frecl
https://crash.limetech.org/247c7a7e3h7m

Issue seems to be pretty widely confirmed within the KZ community after the recent adoption of this plugin. Rolling back to 4037f73 stops the crashes.

**Comment by GAMMACASE** [comment]
That's interesting, I'll do some checks, thanks for the report. Sadly accelerator reports seems to be not that useful as they all unique for some reason, which doesn't make any sense really.

**Comment by GAMMACASE** [comment]
Also is it crashing absolutely randomly, or is there some way to reproduce this behavior?

**Comment by GAMMACASE** [comment]
Also did you compiled all versions yourself? Or for the older one you used release binaries? And some raw views of accelerator reports will also help to track this bug down.

**Comment by GAMMACASE** [comment]
So I've reversed one call stack from one of yours accelerator reports (https://crash.limetech.org/zmvqcz3frecl), and it doesn't seems to be related to this plugin:
```
CBitRead::ReadVarInt32()
CNetMessagePB<15,CCLCMsg_LoadingProgress,0,1>::ReadFromBuffer()
CNetMessageBinder::BindParams<CNetMessagePB<15,CCLCMsg_LoadingProgress,0,1>>::CreateFromBuffer()
CUserMessageBinder::Bind<CCLCMsg_CmdKeyValues_t>()
CBaseClient::ConnectionStart()
CNetChan::Setup()
NET_CreateNetChannel()
CBaseServer::ConnectClient()
CBaseServer::ProcessConnectionlessPacket()
0x37727584 - NET_ProcessSocket()???
CBaseServer::RunFrame()
SV_Frame()
```
And these two reports (https://crash.limetech.org/7k5qdsudjj72 and https://crash.limetech.org/m4ncxggmmvzz) seems to be pointing to some thread related functions, so don't think there's anything useful in there. So, do you use any plugins that are somehow related to player connection or something like this, maybe some session\lobby fix, or my server_redirect plugin, etc.?

**Comment by sneak-it** [comment]
All versions tested were self-compiled against provided includes, SM 1.10 includes, and latest detours15 includes. Seems to crash "randomly", however fairly consistently with a populated server. No known way of reproducing besides tossing on a server with some players and waiting.

I do run your server redirect plugin, however the crash is very reproducible by running commit 38f34e8 . The crashing stops entirely reverting back to 4037f73 - Tested this on multiple servers, multiple times, with unrelated plugins. The crashing happens to other server owners as well with entirely different plugin stacks.

**Comment by GAMMACASE** [comment]
Are you 100% sure that reverting back fixes it? As I'm not see a connection really, as that change in the latest commit is minor and shouldn't really produce some memory corruption (cuz that's what I can think of rn).

**Comment by sneak-it** [comment]
100% certain, the folks developing GOKZ will also be reverting to StoreToAddress shortly and we'll have some more confirmations on that fix.

**Comment by GAMMACASE** [comment]
Well alright, toss some other accelerator logs if you'll get any later, as currently I'm not sure what is the cause of this.

**Comment by GAMMACASE** [comment]
Can you also provide raw view of the reports you sent in main message? (Just a screenshot of webpage when it'll load raw view would be enough)

**Comment by sneak-it** [comment]
I've got a whole stack of them from before I figured out the solution:

https://crash.limetech.org/yuqh3x75pt62
https://crash.limetech.org/ww6qljpavr7x
https://crash.limetech.org/sa5dcnhp3jla
https://crash.limetech.org/3otguzh7iwiq
https://crash.limetech.org/lgzbavpt5oxe
https://crash.limetech.org/ravncsxtc43n
https://crash.limetech.org/couqc3wrtiau

![](https://share.snksrv.com/i/w6ZyOX.png)
![](https://share.snksrv.com/i/NEFkti.png)
![](https://share.snksrv.com/i/6vlWGY.png)

**Comment by GAMMACASE** [comment]
Since I'm not really able to reproduce these crashes and test changes, can you test changes I pushed to here https://github.com/GAMMACASE/MomSurfFix/tree/storetoadressfast_fix ? There were also include file update, so don't forget to update it too.

**Comment by sneak-it** [comment]
I'll go ahead and throw it on a server right now, thank you!

**Comment by sneak-it** [comment]
Hmm, still crashes with that branch.

https://crash.limetech.org/n2k6apzzldol

![](https://share.snksrv.com/i/KNhvif.png)

**Comment by GAMMACASE** [comment]
Hmmm, would you be able go one by one in here https://github.com/GAMMACASE/MomSurfFix/blob/storetoadressfast_fix/addons/sourcemod/scripting/momsurffix/gametrace.sp#L223-L235 and change ``StoreToAddressCustom`` to ``StoreToAddress`` (You might get tag mismatch warning, you can safely ignore them) and see when it stops crashing? These crashes just don't make any sense to me rn lol.

**Comment by GAMMACASE** [comment]
Or actually, I think I have a clue, change these two https://github.com/GAMMACASE/MomSurfFix/blob/storetoadressfast_fix/addons/sourcemod/scripting/momsurffix/gametrace.sp#L229 and https://github.com/GAMMACASE/MomSurfFix/blob/storetoadressfast_fix/addons/sourcemod/scripting/momsurffix/gametrace.sp#L235 to ``StoreToAddress`` and see if it stops these crashes.

**Comment by GAMMACASE** [comment]
Any update here?

**Comment by sneak-it** [comment]
Sorry have been away and very busy (new job), but I will get to this soon!

**Comment by GameChaos** [comment]
> Or actually, I think I have a clue, change these two https://github.com/GAMMACASE/MomSurfFix/blob/storetoadressfast_fix/addons/sourcemod/scripting/momsurffix/gametrace.sp#L229 and https://github.com/GAMMACASE/MomSurfFix/blob/storetoadressfast_fix/addons/sourcemod/scripting/momsurffix/gametrace.sp#L235 to `StoreToAddress` and see if it stops these crashes.

that fixed the problem for me. haven't crashed since.

**Comment by GAMMACASE** [comment]
Alright good to hear, then that could be the cause, as it tries to write 4 byte value to 1 byte and thus causing it to corrupt some other memory that's beyond its structure as these two are the last members in the structure. That also explains absolutely random crash reports.

**Comment by GAMMACASE** [comment]
And yeah, now I remember why I haven't put ``StoreToAddressCustom`` in there, cuz that was the reason. Should've left a comment in there...
